### ISSUE TITLE
[Card Builder] Add a random card feature

### ISSUE THREAD

**Issue by KittySparkles** [Stormbound-Games/stormbound-kitty#777]

**Comment by KittySparkles** [comment]
I played with the concept and couldn’t turn it into something useful so I closed that story. Fortunately for us, someone on Discord pushed the feature quite far and will integrate it into the site.

https://replit.com/@parchmentEngine/Stormbound-Unit-Generator-v2?v=1

**Comment by parchmentEngineer** [comment]
### Current to-do list of features:
- [ ] Add effects that target structures
- [ ] Make Satyr self-base destruction less prevalent
- [ ] Add Dragons, Pirates, Felines, and plain Elders/Ancients
- [ ] Add better filters - maybe even filter for effect classes?
- [ ] Add spells and structures

### Inconsistencies to fix:
- [ ] Affecting bordering/surrounding units with no bordering/surrounding units
- [ ] Spawning units behind when played bordering the base
- [ ] Fix unspent mana calculations
- [ ] Rewrite Convert and Destroy conditions

**Comment by KittySparkles** [comment]
Closing this one as this has been almost 6 months.
